start: "<|begin_of_text|>"
system: "<|start_header_id|>system<|end_header_id|>\n\n{text}<|eot_id|>"
user: "<|start_header_id|>user<|end_header_id|>\n\n{text}<|eot_id|>"
assistant: "<|start_header_id|>assistant<|end_header_id|>\n\n{text}<|eot_id|>"
end: "<|start_header_id|>assistant<|end_header_id|>\n\n"
