start: "<|begin_of_text|>"
roles:
  system: "<|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 Jul 2024\n\n{text}<|eot_id|>"
  user: "<|start_header_id|>user<|end_header_id|>\n\n{text}<|eot_id|>"
  assistant: "<|start_header_id|>assistant<|end_header_id|>\n\n{text}<|eot_id|>"
end: "<|start_header_id|>assistant<|end_header_id|>\n\n"
