# the llama train tokenizer always appends </s>
# as end of sequence token
tokenize:
  type: huggingface
  path: relpath(llama-2/tokenizer.json)
special:
  tokens:
    - <unk>
  pad: <unk>
  suffix:
    - </s>
