# the mistral train tokenizer always appends </s>
# as end of sequence token
tokenize:
  type: huggingface
  path: relpath(mistral/tokenizer.json)
special:
  tokens:
    - <unk>
  pad: <unk>
  suffix:
    - </s>
